#!/bin/sh

NAME=MODULE_NAME
VERSION=MODULE_VERSION

set -e

dkms_deconfigure () {
	if [ "`dkms status -m $NAME`" ]; then
		dkms remove -m $NAME -v $VERSION --all
	fi
	rm -rf /opt/netronome/drv
	rm -f /etc/profile.d/nfp_drv_kmods_dkms_profile.sh
}

case "$1" in
	remove)
		if [ "$2" != "in-favour" ]; then
			/opt/netronome/drv/corigine_pciids revert
		fi
		dkms_deconfigure
	;;

	upgrade|deconfigure)
		dkms_deconfigure
	;;

	failed-upgrade)
	;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
