name: Build

# ========== TRIGGER ==========

on:
  push:
    branches:
      - main            # default branch name
      - '*-build*'      # Temporary build, no testing
      - '*build-*'      # Temporary build, no testing
      - 'prerelease-*'  # Prerelease build
      - 'release-*'     # Release build
      - '*.check'
  # Schedule run at midnight daily
  schedule:
    - cron: '0 0 * * *'
  # External calling
  workflow_call:
    inputs:
      target_ref:
        description: >
          SHA, Branch, or Tag to build.
        default: ''
        type: string

env:
  DOWNLOAD: ".download"
  UNPACKED: ".unpacked"

jobs:
  build-centos:
    name: 'Build-CentOS: ${{matrix.release.name}}'
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    env:
      KVER: "*"
    strategy:
      matrix:
        release: [
                # CentOS
                { "name": "7.0.1406", "container": "centos:7.9.2009" },
                { "name": "7.1.1503", "container": "centos:7.9.2009" },
                { "name": "7.2.1511", "container": "centos:7.9.2009" },
        ]
    container:
      image: ${{ matrix.release.container }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: '${{ inputs.target_ref }}'

      - name: Temporary one
        run: echo $GITHUB_WORKSPACE

      - name: Temporary two
        run: git log --oneline | head -10

      - name: Set Download Environment
        env:
          RELEASE_NAME: ${{ matrix.release.name }}
        run: |
          case $RELEASE_NAME in
          7.[0-8].*|8.[0-5].*) MIRROR="vault.centos.org" ;;
          8.[6-8])             MIRROR="dl.rockylinux.org/vault/rocky" ;;
          8.9)                 MIRROR="dl.rockylinux.org/pub/rocky" ;;
          9.[0-2])             MIRROR="dl.rockylinux.org/vault/rocky" ;;
          9.[3-9])             MIRROR="dl.rockylinux.org/pub/rocky" ;;
          9-*)                 MIRROR="mirror.stream.centos.org" ;;
          *)                   MIRROR="mirror.centos.org/centos" ;;
          esac

          case $RELEASE_NAME in
          7.*)    OS_DIR1="os"
                  OS_DIR2=""
                  ;;
          8*)     OS_DIR1="BaseOS"
                  OS_DIR2="os"
                  ;;
          9*)     OS_DIR1="AppStream"
                  OS_DIR2="os"
                  ;;
          esac

          case $RELEASE_NAME in
          9.*)    OS_PATH="$MIRROR/$RELEASE_NAME/$OS_DIR1/x86_64/$OS_DIR2/Packages/k/"
                  ;;
          8.[6-9])    OS_PATH="$MIRROR/$RELEASE_NAME/$OS_DIR1/x86_64/$OS_DIR2/Packages/k/"
                  ;;
          *)      OS_PATH="$MIRROR/$RELEASE_NAME/$OS_DIR1/x86_64/$OS_DIR2/Packages/"
          esac

          UPDATE_PATH="$MIRROR/$RELEASE_NAME/updates/x86_64/$OS_DIR2/Packages/"
          echo "OS_PATH=$OS_PATH" >> $GITHUB_ENV
          echo "UPDATE_PATH=$UPDATE_PATH" >> $GITHUB_ENV

      - name: Cache OS Kernel Header Packages
        uses: actions/cache@v3
        env:
          cache-name: cache-os-headers
        with:
          path: ${{ env.DOWNLOAD }}/${{ env.OS_PATH }}
          key: ${{ env.cache-name }}-${{ matrix.release.name }}-v1

      - name: Cache Update Kernel Header Packages
        if: startsWith(matrix.release.name, '7')
        uses: actions/cache@v3
        env:
          cache-name: cache-update-headers
        with:
          path: ${{ env.DOWNLOAD }}/${{ env.UPDATE_PATH }}
          key: ${{ env.cache-name }}-${{ matrix.release.name }}-v1

      - name: Install Dependencies
        run: yum -q -y install cpio elfutils-libelf-devel findutils gcc make wget ca-certificates

      - name: Filter CentOS stream 8 kernel
        if: startsWith(matrix.release.name, '8-stream')
        run: |
          KVER=$(curl -s "http://${{ env.OS_PATH }}/" | \
            sed -En 's/.*kernel-devel-(4.18.0-[0-9].*).el8.*rpm.*/\1/p' | \
            tail -n 1)
          echo $KVER
          echo "KVER=${KVER}*" >> $GITHUB_ENV

      - name: Filter CentOS stream 9 and RHEL 9 kernels
        if: startsWith(matrix.release.name, '9')
        run: |
          KVER=$(curl -s "http://${{ env.OS_PATH }}/" | \
            sed -En 's/.*kernel-devel-(5.14.0-[0-9].*).el9*rpm.*/\1/p' | \
            tail -n 1)
          echo $KVER
          echo "KVER=${KVER}*" >> $GITHUB_ENV

      - name: Download OS Kernel Header Packages
        uses: ./.github/actions/download
        with:
            output-path: ${{ env.DOWNLOAD }}
            url: "http://${{ env.OS_PATH }}"
            accept: "kernel-devel-${{ env.KVER }}.rpm"

      - name: Download Update Kernel Header Packages
        if: startsWith(matrix.release.name, '7')
        uses: ./.github/actions/download
        with:
            output-path: ${{ env.DOWNLOAD }}
            url: "http://${{ env.UPDATE_PATH }}"
            accept: "kernel-devel-${{ env.KVER }}.rpm"

      - name: Unpack Kernel Headers
        uses: ./.github/actions/unpack-rpm
        with:
            input-path: ${{ env.DOWNLOAD }}
            output-path: ${{ env.UNPACKED }}

      - name: Build
        uses: ./.github/actions/build
        with:
            search-path: "${{ env.UNPACKED }}/usr/src/kernels"
