name: Coordinate NFP-DRV-KMODS Workflows

# ========== TRIGGER ==========
on:
  push:
    branches:
      - 'public-main' # Or other default branch name
      - 'test-*'      # Temporary test build
      - 'build-*'     # Temporary build, no testing
      - 'release-*'   # Release build
  workflow_dispatch:

jobs:
  package_dkms:
    uses: ./.github/workflows/package-dkms.yaml
    secrets:
      AZ_SAS_TOK: ${{ secrets.AZ_SAS_TOK }}
      GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

  install_dkms_packages:
    needs: package_dkms
    uses: ./.github/workflows/ci-test-interop.yaml
    secrets:
      AZ_SAS_TOK: ${{ secrets.AZ_SAS_TOK }}
      GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
