# Run linting actions to check for trailing whitespace,
# spelling, commit message, and code format issues.
name: Linter/commit check

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  linters:
    uses: Corigine/ci-libs/.github/workflows/ci-linting.yaml@main
    with:
      json_config: >-
        {"commit_check": ${{ vars.lint_conf_commit || '{}' }},
        "code_check": ${{ vars.lint_conf_code || '{}' }},
        "spell_check": ${{ vars.lint_conf_spell || '{"fail_flag": true}' }}
        ${{ vars.lint_conf_other }}
        }
      enabled_linters: >-
        ${{ vars.lint_commits || 'commit_check' }},
        ${{ vars.lint_coding || 'code_check' }},
        ${{ vars.lint_spelling || 'spell_check' }},
        ${{ vars.lint_other }}
    secrets: inherit
