name: Sync local kernels

# ========== TRIGGER ==========

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:
    secrets:
      GHUB_TOKEN:
        required: true
      AZ_SAS_TOK:
        required: true
  workflow_dispatch:
    secrets:
      GHUB_TOKEN:
        required: true
      AZ_SAS_TOK:
        required: true

jobs:
  sync-local:
    name: Sync local kernels
    runs-on:
      - self-hosted
      - ci-linter-vm
    env:
      LOCAL_KERNELS: tmp/misc/kernel-devel-c4c
    steps:
      # --- PREPARE ENVIRONMENT ---
      - name: Clean up the working directory
        run: sudo find -delete

      # --- CLONE REPOSITORIES ---
      - name: Checkout repo
        uses: Corigine/ci-libs/github_actions/utilities/checkout_corigine@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GHUB_TOKEN }}

      - name: Clone ci-libs (for other GH actions)
        uses: Corigine/ci-libs/github_actions/utilities/checkout_corigine@main
        with:
          repository: Corigine/ci-libs
          token: ${{ secrets.GHUB_TOKEN }}
          path: ci-libs

      - name: Get local buildinfo.json files
        id: local-buildinfo
        uses: Corigine/ci-libs/github_actions/azure/azcopy_download@main
        with:
          connection-string: ${{ secrets.AZ_SAS_TOK }}
          src: ${{ env.LOCAL_KERNELS }}
          dst: latest/
          pattern: '*buildinfo.json'

      - name: Get local kernel-devel packages
        id: local-kernels
        uses: Corigine/ci-libs/github_actions/azure/azcopy_list@main
        with:
          connection-string: ${{ secrets.AZ_SAS_TOK }}
          src: ${{ env.LOCAL_KERNELS }}

      - name: Get latest kernel-devel rpms
        id: up-to-date
        shell: bash
        run: |
          UP_TO_DATE=true

          for DIR in latest/kernel-devel-c4c/*; do
            OS=${DIR##*/}
            MIRROR=$(sed -n 's/.*\"mirror\": \"\(.*\)\"/\1/p' $DIR/buildinfo.json)
            if [[ "${OS}" != "opensuse"* ]]; then
              (
                sudo wget -r --spider -o $DIR/packages.txt --no-parent \
                  "${MIRROR}" -A 'kernel-devel*'

                PACKAGES=$(grep -o "kernel-devel.*\.rpm$" $DIR/packages.txt)

                PRESENT=$(echo "${{ steps.local-kernels.outputs.file-list }}" | grep -o "$dir[^ ]*rpm" || true)
                for package in $PACKAGES; do
                  if [[ "$PRESENT" != *"$package"* || "$PRESENT" == "" ]]; then
                    echo "::notice::$package not present locally"
                    echo "${MIRROR}/$package" | sudo tee -a $DIR/downloads.txt
                  fi
                done

                sudo wget -q -i $DIR/downloads.txt -P $DIR/
              ) &
            fi
          done
          wait

          if [[ $(find latest -type f -name downloads.txt) ]]; then
            UP_TO_DATE=false
          fi

          find latest -type f -name "downloads.txt" -delete \
                              -o -name "packages.txt" -delete

          echo  "UP_TO_DATE=${UP_TO_DATE}" | tee -a $GITHUB_OUTPUT

      - name: Upload new kernel-devel binaries to Azure
        if: steps.up-to-date.outputs.UP_TO_DATE == 'false'
        uses: Corigine/ci-libs/github_actions/azure/azcopy_upload@main
        with:
          connection-string: ${{ secrets.AZ_SAS_TOK }}
          src: latest/kernel-devel-c4c/*
          dst: ${{ env.LOCAL_KERNELS }}

  build-local:
    if: always()
    needs: sync-local
    uses: ./.github/workflows/build-local.yaml
    secrets:
      AZ_SAS_TOK: ${{ secrets.AZ_SAS_TOK }}
      GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
